#!/bin/zsh

MAIL=`echo $1 | sed 's/mailto://'`

i3-msg scratchpad show
xdotool search --name "^Sup" key --window %@ m
xdotool search --name "^Sup" type --window %@ "$MAIL"
xdotool search --name "^Sup" key --window %@ Return
