---
:editor: vim -f -c 'set ft=mail' -c 'set textwidth=0' '+/^\s*\n/' '+nohl'
:thread_by_subject: false
:edit_signature: false
:ask_for_from: false
:ask_for_to: true
:ask_for_cc: true
:ask_for_bcc: false
:ask_for_subject: true
:account_selector: true
:confirm_no_attachments: true
:confirm_top_posting: false
:jump_to_open_message: true
:discard_snippets_from_encrypted_messages: false
:load_more_threads_when_scrolling: true
:default_attachment_save_dir: ''
:sent_source: "sup://sent"
:archive_sent: true
:poll_interval: 300
:wrap_width: 0
:slip_rows: 0
:col_jump: 2
:stem_language: english
:sync_back_to_maildir: true
:continuous_scroll: false
:always_edit_async: false
:accounts:
  :default:
    :name: Francisco Penedo
    :email: fran.penedo@gmail.com
    :alternates:
    :sendmail: "msmtp -t --read-envelope-from"
    :signature: "/home/fran/.signature"
    :gpgkey: ''
  :bu:
    :name: Francisco Penedo
    :email: franp@bu.edu
    :alternates:
    :sendmail: "msmtp -a bu -t --read-envelope-from"
    :signature: "/home/fran/.signature"
    :gpgkey: ''
:time_mode: 24h
